### PR TITLE
Design Changes

### PR DESCRIPTION
**Pull request by rjalfa**
- PEP8

### CODE REVIEW

**Comment by divamgupta** [comment]
Thanks for the PR. I will review and merge it shortly.

**Comment by divamgupta** [comment]
Hi,

In your PR, you have added Keras 2.3.0 and Tensorflow as a hard requirement. We want it to be compatible with tensorflow / theano / cntk. And keras >= 2.0.0 .  And it should be tested with all tensorflow, theano and cntk

**Comment by divamgupta** [comment]
@rjalfa And it would be good if we can get rid of opencv.

**Comment by rjalfa** [comment]
> Hi,
> 
> In your PR, you have added Keras 2.3.0 and Tensorflow as a hard requirement. We want it to be compatible with tensorflow / theano / cntk. And keras >= 2.0.0 . And it should be tested with all tensorflow, theano and cntk

This is now done (the setup.py part that is). Yet to add tests though

**Pull request merged**
