### PR TITLE
Adds customization options to the segmentation models and other improvements

### PR DESCRIPTION
**Pull request by Marius-Juston**
Main additions:
Adds the ability to add custom callbacks to the model training sequences
Adds the ability to add custom augmentation functions to the model training
Adds the ability to add multi-image input with data augmentation to the models easily

Minor additions:
Uses TensorFlow model checkpoint instead of custom Keras one.
Uses tensorflow tf.train.latest_checkpoint function instead of custom find_latest_checkpoint function
Updates some of the deprecated augmentation function classes (using imgaug>=0.4.0)
For the auto-resume checkpoint boolean in training makes it so that it continues from the last checkpoint epoch number instead from 0 again
Uses the model.fit function instead of the model.fit_generator function
If the checkpoint base folder does not exist, create it
Updates the dataset visualization part of the library to accommodate different augmentation functions and image size

### CODE REVIEW

**Comment by Marius-Juston** [comment]
I believe that the Python 2.7 tests should be removed since Python 2 has been deprecated. Also, I think that imgaug and imageio should be updated to their latest versions.

The current versions being used are 2.5.0 for imageio and imgaug 0.2.9 while the newer versions are 2.9.0 and 0.4.0 respectively. Though I do not know exactly how to update the library requirements

**Comment by Marius-Juston** [comment]
Yay all green!!

@divamgupta I hope that this helps the community and it would be great if you checked out my changes! (this is my first pull request so any feedback would be greatly appreciated! )

**Comment by divamgupta** [comment]
Hi @Marius-Juston thanks for the pull request. I will review it and get back to you.

**Comment by Marius-Juston** [comment]
Just added some unit tests to verify everything works for the data generator functions

**Comment by Marius-Juston** [comment]
Added the ability to change the number of image input channels to the models.
Also fixed a mistake in the default fcn_8_mobilenet and fcn_32_mobilenet input height and width

**Comment by Marius-Juston** [comment]
@divamgupta I believe that I am done with my changes/feature additions. Sorry about that!

**Comment by Marius-Juston** [comment]
Okay now this was the last thing

**Comment by divamgupta** [comment]
@Marius-Juston Thanks for the good work. I have merged the PR. If you want, you could also update the readme for the new features.

**Comment by Marius-Juston** [comment]
Will do!

**Pull request merged**
