### PR TITLE
video prediction function callable from CLI

### LINKED ISSUE #83: Segmenting image stream
@divamgupta Is it possible to run the segmentation on an image stream/video?

### PR DESCRIPTION
**Pull request by JaledMC**
Takes a local video or webcam stream, obtains the inference mask, and overlays it over original frame for better representation.

I tried to follow your repo code style, but there is code duplicity between this function and `predict()`.

It expects weights path, the input video source, and, if desired, the frame speed.

Fixes #83 

Thanks for this amazing repo and hope it helps.

### CODE REVIEW

**Comment by divamgupta** [comment]
Hi,
Thanks for the PR. I think it will better calling `keras_segmentation.predict.predict` from `predict_video`. Then there wont be any duplicity and parameters such as `show_legends` , `overlay_img` etc can also be supported.

**Comment by JaledMC** [comment]
Good point! Done with `predict` and `overlay_img`. CLI parameters similar to `predict`.

PS: in my Nvidia GTX 1050, inference is about 10 fps. With `overlay_img`, it drops to 7.5 fps :scream: , because this line in `overlay_seg_image`: 
```
fused_img = (inp_img/2 + seg_img/2).astype('uint8')
```
Some changes with other numpy and OpenCV functions give the same results. I'm surprised by the impact of a simple matrix operation. Coding is amazing.

**Comment by divamgupta** [comment]
Thanks! One other thing, as most of the users work on headless servers, doing an imshow is not an option. I think it will be better to specify the name of the output video file rather than doing imshow by default. We could add an optional parameter ( which is set to False by default ) to visualise the output via imshow.

**Comment by JaledMC** [comment]
That's true. Added two parameters:
*  `--output_file`, to save inference video. If empty, no video is saved.
* `--display`. If we pass this parameter, new window with inference video appears. 

`--speed` is not needed anymore, because Opencv reads the original fps of the source, both for saving the file and video representation. More simple and more similar to `predict` function.

PS: private function `set_video`, which encode the output_file, to keep `predict_video` cleaner and modular. 

Let me know if you prefer any change.

Happy coding!

**Comment by divamgupta** [comment]
Looks good. Thanks a lot.

**Comment by divamgupta** [comment]
You might want to add the instructions for video prediction in the readme.

**Comment by JaledMC** [comment]
Of course! Good job is not done until documented. New pull request with documentation created.

**Pull request merged**
